### PR TITLE
[Fix] Modified to work with pytorch version 1.0

### PR DESCRIPTION
**Pull request by kiddj**
Fix some codes for compatibility with pytorch verison 1.0.
The fixes covered in the github issue are also included.

Tested in pytorch 1.0, CUDA 10.0 in Ubuntu 16.04,
and used latest version of fastText. (https://github.com/facebookresearch/fastText)

Since the version of pytorch changes, README also has been slightly modified.

### CODE REVIEW

**Comment by woozzu** [comment]
@kiddj Thank you for your contribution. Would you refer to the link of the GitHub issue?

**Comment by kiddj** [comment]
I referenced the issues in https://github.com/woozzu/tagan/issues.

**Comment by woozzu** [comment]
@kiddj Please let me know which issues did you address in this PR. Thanks!

**Comment by kiddj** [comment]
@woozzu I tried to fix some problems caused by
fastText (https://github.com/woozzu/tagan/issues/1) and pytorch (https://github.com/woozzu/tagan/issues/4) which already mentioned in github issue.

I think both are version compatibility issues. Thanks :)

**Comment by woozzu** [comment]
@kiddj Thanks! LGTM.

**Pull request merged**
